$ErrorActionPreference = 'Stop'


Uninstall-ChocolateyFont "FiraMono-Bold.otf"
Uninstall-ChocolateyFont "FiraMono-Medium.otf"
Uninstall-ChocolateyFont "FiraMono-Regular.otf"


Uninstall-ChocolateyFont "FiraSans-Bold.otf"
Uninstall-ChocolateyFont "FiraSans-BoldItalic.otf"
Uninstall-ChocolateyFont "FiraSans-Book.otf"
Uninstall-ChocolateyFont "FiraSans-BookItalic.otf"
Uninstall-ChocolateyFont "FiraSans-Eight.otf"
Uninstall-ChocolateyFont "FiraSans-EightItalic.otf"
Uninstall-ChocolateyFont "FiraSans-ExtraBold.otf"
Uninstall-ChocolateyFont "FiraSans-ExtraBoldItalic.otf"
Uninstall-ChocolateyFont "FiraSans-ExtraLight.otf"
Uninstall-ChocolateyFont "FiraSans-ExtraLightItalic.otf"
Uninstall-ChocolateyFont "FiraSans-Four.otf"
Uninstall-ChocolateyFont "FiraSans-FourItalic.otf"
Uninstall-ChocolateyFont "FiraSans-Hair.otf"
Uninstall-ChocolateyFont "FiraSans-HairItalic.otf"
Uninstall-ChocolateyFont "FiraSans-Heavy.otf"
Uninstall-ChocolateyFont "FiraSans-HeavyItalic.otf"
Uninstall-ChocolateyFont "FiraSans-Light.otf"
Uninstall-ChocolateyFont "FiraSans-LightItalic.otf"
Uninstall-ChocolateyFont "FiraSans-Medium.otf"
Uninstall-ChocolateyFont "FiraSans-MediumItalic.otf"
Uninstall-ChocolateyFont "FiraSans-SemiBold.otf"
Uninstall-ChocolateyFont "FiraSans-SemiBoldItalic.otf"
Uninstall-ChocolateyFont "FiraSans-Thin.otf"
Uninstall-ChocolateyFont "FiraSans-ThinItalic.otf"
Uninstall-ChocolateyFont "FiraSans-Two.otf"
Uninstall-ChocolateyFont "FiraSans-TwoItalic.otf"
Uninstall-ChocolateyFont "FiraSans-Ultra.otf"
Uninstall-ChocolateyFont "FiraSans-UltraItalic.otf"
Uninstall-ChocolateyFont "FiraSans-UltraLight.otf"
Uninstall-ChocolateyFont "FiraSans-UltraLightItalic.otf"
Uninstall-ChocolateyFont "FiraSans-Regular.otf"
Uninstall-ChocolateyFont "FiraSans-Italic.otf"


Uninstall-ChocolateyFont "FiraSansCondensed-Bold.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-BoldItalic.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-Book.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-BookItalic.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-Eight.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-EightItalic.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-ExtraBold.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-ExtraBoldItalic.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-ExtraLight.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-ExtraLightItalic.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-Four.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-FourItalic.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-Hair.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-HairItalic.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-Heavy.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-HeavyItalic.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-Light.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-LightItalic.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-Medium.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-MediumItalic.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-SemiBold.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-SemiBoldItalic.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-Thin.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-ThinItalic.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-Two.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-TwoItalic.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-Ultra.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-UltraItalic.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-UltraLight.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-UltraLightItalic.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-Regular.otf"
Uninstall-ChocolateyFont "FiraSansCondensed-Italic.otf"
